In [12]:
import numpy as np

In [44]:
x

matrix([[1],
        [1]])

In [45]:
y

matrix([[1, 2, 3]])

In [49]:
z

matrix([[1, 2, 3],
        [1, 2, 3]])

In [46]:
np.kron(y.T, np.eye(2))

matrix([[1., 0.],
        [0., 1.],
        [2., 0.],
        [0., 2.],
        [3., 0.],
        [0., 3.]])

In [57]:
np.kron(np.eye(2),y.T)

matrix([[1., 0.],
        [2., 0.],
        [3., 0.],
        [0., 1.],
        [0., 2.],
        [0., 3.]])

In [75]:
import numpy as np
x=np.matrix([[1.0],[1.0]])
y = np.matrix([1.0,2.0,3.0])
z = x.dot(y)
z

matrix([[1., 2., 3.],
        [1., 2., 3.]])

In [76]:
x

matrix([[1.],
        [1.]])

In [70]:
grad = np.zeros((6,2))

In [71]:

idxs00 = 0
idxs01 = 0
for i in range(2):
    for j in range(3):
        for l in range(2):
            for k in range(1):
                idxs00 = i*3+j
                idxs01 = i*1+k
                if(i == l):
                    idxs10 = k
                    idxs11 = j
                    grad[idxs00,idxs01] = y[idxs10,idxs11]
                    
                

In [72]:
grad

array([[1., 0.],
       [2., 0.],
       [3., 0.],
       [0., 1.],
       [0., 2.],
       [0., 3.]])

In [73]:
# x ->6
# 2
for i in range(6):
    for j in range(2):
        x[j] += grad[i,j]


In [74]:
x

matrix([[7.],
        [7.]])

In [63]:
grad2 = np.zeros((6,3))

In [70]:
idxs00 = 0
idxs01 = 0
for i in range(2):
    for j in range(3):
        for l in range(1):
            for k in range(3):
                idxs00 = i*3+j
                idxs01 = l*3+k
                if(j == k):
                    idxs10 = i
                    idxs11 = l
                    grad2[idxs00,idxs01] = x[idxs10,idxs11]

In [71]:
grad2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
import numpy as np
x = np.matrix([[0.2],[0.4]])
w = np.matrix([[0.1,0.5],[-0.3,0.8]])
q = np.matrix([[0.22],[0.26]])

In [15]:
c = 2*w.dot(x)
c.T.dot(w)

matrix([[-0.112,  0.636]])

In [26]:
import numpy as np
#a = np.matrix([[1,0],[0,1]])
a = np.matrix([[0],[0],[0],[0]])
b = np.matrix([[2,0,0,0],[0,3,0,0],[0,0,7,0],[0,0,0,15]])
for i in range(4):
    for j in range(4):
        a[j] += b[i,j]
a

matrix([[ 2],
        [ 3],
        [ 7],
        [15]])

In [25]:
a

matrix([[2],
        [3],
        [0],
        [0]])

In [19]:
import numpy as np
b = np.matrix([[2,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [21]:
b[0,0]

2